"""Freshness checks -- is today's data actually here yet?

The asset checks in checks.py validate *quality* once an asset
materializes (row counts, null rates). These validate *timeliness*
independent of whether a materialization ran at all: each check fails if
an asset's last materialization is older than expected relative to the
daily schedule in definitions.py, so a silently skipped or broken schedule
shows up as a red check in the Assets UI instead of a mart that just
quietly stops updating with nothing to notice.

Uses build_last_update_freshness_checks rather than the newer
FreshnessPolicy (attached directly on an asset's spec at definition time):
FreshnessPolicy works cleanly for the plain @asset-decorated raw sources
below, but the mart assets are auto-generated by @dbt_assets as one
multi-asset from the dbt manifest, not individually decorated -- there's
no per-model place to attach a policy without a more invasive custom
DagsterDbtTranslator. The check-based builder works uniformly across both,
referencing any asset by key regardless of how it was defined, at the
cost of a (functioning, non-breaking) SupersessionWarning on import.
"""

from datetime import timedelta

import dagster as dg

# Matches the daily schedule in definitions.py: the whole ingest -> fx ->
# dbt build pipeline is expected to have completed shortly after 6am UTC.
_DEADLINE_CRON = "0 6 * * *"

# Raw ingestion: observed to complete in well under a minute per source
# (see CI run times). Two hours leaves generous room for a retried or slow
# day without papering over a genuinely missed run.
raw_freshness_checks = dg.build_last_update_freshness_checks(
    assets=["ameyo_calls", "atlas_dispositions", "payments", "agent_mapping", "fx_rates"],
    deadline_cron=_DEADLINE_CRON,
    lower_bound_delta=timedelta(hours=2),
)

# Marts: what the dashboard and any BI consumer actually reads. These
# materialize after the raw layer via dbt build, so their window is the
# raw layer's two hours plus room for the transform itself to run.
mart_freshness_checks = dg.build_last_update_freshness_checks(
    assets=[
        dg.AssetKey(["marts", "agg_daily_summary"]),
        dg.AssetKey(["marts", "fct_coding_rate"]),
        dg.AssetKey(["marts", "fct_paid_post_call"]),
        dg.AssetKey(["marts", "fct_inbound_call_drivers"]),
    ],
    deadline_cron=_DEADLINE_CRON,
    lower_bound_delta=timedelta(hours=3),
)

freshness_checks = [*raw_freshness_checks, *mart_freshness_checks]
